name: Jest Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    strategy:
      matrix:
        node-version: [18.x, 20.x, 21.x]

    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn install

      - name: Add secrets to .env
        run: |
          echo "HEBE_USERNAME=${{ secrets.HEBE_USERNAME }}" >> .env
          echo "HEBE_PASSWORD=${{ secrets.HEBE_PASSWORD }}" >> .env

      - name: Run Jest tests
        run: yarn test
